"""Signal specification types -- v4 (unified Entries/Exits, signed weights).

A ``Signal`` is an OR of AND-blocks of boolean conditions split into two
sections: ``entries`` and ``exits``. Each entry block has a **signed**
weight in ``[-100, +100]`` (percentage of capital, sign decides long/
short). Each exit block references **one or more** entry blocks via
``target_entry_block_names`` and, when its conditions latch, clears the
latch of every targeted entry that is currently open — those entries may
live on different inputs (cross-input exits are allowed).

v4 contract (breaks v3 — no migration, no compat shims)
-------------------------------------------------------
* ``SignalRules`` now has ``entries: tuple[Block, ...]`` and
  ``exits: tuple[Block, ...]``. The v3 four-direction split is gone.
* ``Block`` carries a stable ``id: str`` (UUID generated by the
  frontend on block creation), a user-editable ``name: str``, a signed
  ``weight``, and — on exit blocks only — a
  ``target_entry_block_names: tuple[str, ...]`` referencing the
  ``name`` of one or more entry blocks declared in the same signal's
  rules.
* Exits clear the latch of every entry block named in
  ``target_entry_block_names`` (that is currently latched) at the firing
  bar — never "all latches under the same input". Targets may span
  multiple inputs.
* Entries use ``sign(weight)`` as direction. ``weight == 0`` on entry
  blocks is invalid (meaningless, matches the old strictly-positive
  constraint transposed).

Inputs are still a top-level list; blocks and operands still bind
through ``input_id``. Instrument and indicator operand resolution are
unchanged from v3.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

from tcg.types.options import MaturitySpec, RollOffset, SelectionCriterion


# ---------------------------------------------------------------------------
# Input instrument (discriminated union)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class InstrumentSpot:
    """Spot instrument — a single (collection, instrument_id)."""

    collection: str
    instrument_id: str
    kind: Literal["spot"] = "spot"


@dataclass(frozen=True)
class InstrumentContinuous:
    """Continuous-futures instrument — rolled from a FUT_* collection."""

    collection: str
    adjustment: Literal["none", "ratio", "difference"] = "none"
    cycle: str | None = None  # e.g. "HMUZ" quarterly
    roll_offset: int = 0
    # Issue #3: ``end_of_month`` rolls on the last trading day of each month
    # regardless of expiry; default ``front_month`` keeps existing specs valid.
    strategy: Literal["front_month", "end_of_month"] = "front_month"
    kind: Literal["continuous"] = "continuous"


# Streams readable off a single option contract row.  Mirrors the engine
# ``StreamLabel`` and the API ``OptionStreamLabel`` — redeclared here so
# the types layer has no dependency on engine or core.
#
# ``bs_mid`` is a COMPUTED premium (not a row field): the contract's Black-76
# theoretical price from its stored IV + the underlying FUTURE price (the Java
# sim's price basis), intrinsic at expiry.  Like ``mid`` it is a price-like
# premium (usable as a P&L series), unlike the iv/greek/volume LEVEL streams.
OptionStreamLabel = Literal[
    "mid",
    "bs_mid",
    "iv",
    "delta",
    "gamma",
    "vega",
    "theta",
    "open_interest",
    "volume",
]


@dataclass(frozen=True)
class InstrumentOptionStream:
    """Option-stream instrument — materialises a 1-D float stream off a
    selected option contract on each trade date.

    Uses the same maturity/selection/stream vocabulary as the indicator
    and options routers so a signal can bind to an option-derived series
    (e.g. 25-delta put IV, front-month mid price) without inventing a
    parallel spec.
    """

    collection: str
    option_type: Literal["C", "P"]
    cycle: str | None
    maturity: MaturitySpec
    selection: SelectionCriterion
    stream: OptionStreamLabel
    # Roll offset — the ROLL-EARLY axis: ``RollOffset(value, unit='days'|'months')``.
    # The resolver evaluates the maturity rule as of ``date + offset`` so every
    # roll fires that much earlier.  Default ``RollOffset()`` (value 0) = no shift.
    # DISTINCT from the maturity's ``offset_months`` (TARGET-month axis).
    #
    # NOTE: "roll at end of month" is the ``EndOfMonth`` maturity (which makes the
    # resolver hold one contract per month), NOT a roll-offset value — the former
    # separate ``roll_schedule`` field was removed.  And unlike
    # :class:`InstrumentContinuous` (futures), option streams carry NO
    # back-adjustment (the series is always the raw stitched stream).
    roll_offset: RollOffset = field(default_factory=RollOffset)
    # SELECT-AND-HOLD (default False = current daily-reselect behaviour).  When
    # True, the series resolver picks the contract ONCE per maturity roll, HOLDS
    # it between rolls, and emits the per-date HELD-CONTRACT PREMIUM (mid) LEVEL +
    # roll info; signal_exec then runs the FIXED-CONTRACT DOLLAR-P&L recurrence
    # (size a held quantity once per roll off the compounding NAV and the roll
    # premium, book qty·Δpremium daily, realise+resize at the next roll — the
    # ground-truth Java sim, oracle-exact).  NOT a stitched level / no option
    # ratio-adjust.  Fixes the meaningless P&L a ByDelta/ByMoneyness option signal
    # otherwise gets (option %-returns EXPLODE as a held premium decays toward 0).
    # The correct mode for backtesting a delta-selected option; the default stays
    # the raw daily-reselect mid LEVEL (Data-page/chart display).
    hold_between_rolls: bool = False
    # PREMIUM-NOTIONAL MULTIPLE for the fixed-contract dollar-P&L sizing (hold mode
    # only).  The held quantity at each roll is ``nav_times · NAV_at_roll /
    # premium_at_roll`` (the Java ``AllocationProcessNavTimes`` multiple), so
    # nav_times is the size and the DIRECTION (long/short) comes from the block
    # WEIGHT SIGN as usual.  nav_times can exceed 1 (leverage on the premium
    # notional), which the weight ∈ [-100, 100] cannot express — that is why it is
    # a separate field.  Ignored when ``hold_between_rolls`` is False (the default
    # daily-reselect / display path takes the ordinary weight-only price return).
    nav_times: float = 1.0
    kind: Literal["option_stream"] = "option_stream"


# A single leg of an :class:`InstrumentBasket`.  Each leg pairs one of
# the three concrete leaf instrument types (``InstrumentSpot`` /
# ``InstrumentContinuous`` / ``InstrumentOptionStream``) with a signed
# ``float`` weight.  Tuple-of-tuples representation chosen over a
# wrapper dataclass to minimise churn in the engine / fetcher / overlap
# / identity paths — those code paths already pattern-match on the
# leaf instrument types, so unpacking ``(instrument, weight)`` per leg
# requires no new ``isinstance`` chains.


@dataclass(frozen=True)
class InstrumentBasket:
    """Basket instrument — saved or inline.

    Two shapes converge into this single dataclass after API-layer
    resolution so downstream code (fetcher, overlap, identity, payload)
    does not need to branch on origin:

    * **Saved basket** (``basket_id is not None``): a reference to a
      persisted ``BasketDoc``. The basket's legs are resolved from the
      DB by ``_resolve_basket_inputs`` and materialised into the
      polymorphic leg shape.
    * **Inline basket** (``basket_id is None and asset_class is not None``):
      legs come from the wire payload, each leg's ``instrument``
      sub-object dispatched into the matching leaf type by
      ``_parse_input``.

    ``legs`` is a tuple of ``(instrument, weight)`` pairs where
    ``instrument`` is one of :class:`InstrumentSpot`,
    :class:`InstrumentContinuous`, or :class:`InstrumentOptionStream`.
    The per-leg instrument carries its own ``collection`` (and
    adjustment / cycle / etc. for the rolled / option-stream shapes),
    so the basket-level ``collection`` field that earlier iterations
    carried is no longer needed and has been dropped.

    ``asset_class`` is non-``None`` for inline baskets and saved
    baskets (carried on the envelope so the identity hash can
    discriminate ``equity`` vs ``index`` baskets of the same spot
    legs).  It is used by ``_instrument_identity`` to compute a
    structural identity for inline baskets.
    """

    legs: tuple[
        tuple["InstrumentSpot | InstrumentContinuous | InstrumentOptionStream", float],
        ...,
    ]
    basket_id: str | None = None
    asset_class: str | None = None
    kind: Literal["basket"] = "basket"


InputInstrument = (
    InstrumentSpot | InstrumentContinuous | InstrumentOptionStream | InstrumentBasket
)


@dataclass(frozen=True)
class Input:
    """A named price-series input declared at the top of a signal.

    ``id`` is typically a single letter (X, Y, Z, ...) assigned
    automatically on creation and user-renameable. ``instrument`` is the
    fully-configured source; an unconfigured input (missing collection
    or instrument_id, missing cycle/adjustment for continuous) is not
    runnable.
    """

    id: str
    instrument: InputInstrument


# ---------------------------------------------------------------------------
# Operand
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class IndicatorOperand:
    """Operand backed by a user-defined indicator.

    ``input_id`` identifies the bound input; the input's instrument
    replaces the indicator's primary series-map instrument at execution
    time. ``series_override`` maps ``label -> input_id`` to rebind
    non-primary labels to other declared inputs. ``params_override``
    maps ``param_name -> value``.
    """

    indicator_id: str
    input_id: str
    output: str = "default"
    params_override: dict[str, Any] | None = None
    series_override: dict[str, str] | None = None  # label -> input_id
    kind: Literal["indicator"] = "indicator"


@dataclass(frozen=True)
class InstrumentOperand:
    """Operand backed by an input's price field (default: ``close``).

    ``input_id`` references one of the signal's declared inputs; the
    operand resolves through that input's bound instrument.
    """

    input_id: str
    field: str = "close"
    kind: Literal["instrument"] = "instrument"


@dataclass(frozen=True)
class ConstantOperand:
    """Operand backed by a constant scalar broadcast across all timesteps."""

    value: float
    kind: Literal["constant"] = "constant"


Operand = IndicatorOperand | InstrumentOperand | ConstantOperand


# ---------------------------------------------------------------------------
# Condition variants (unchanged vs v2)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CompareCondition:
    """Binary comparison: ``lhs <op> rhs`` for ``gt|lt|ge|le|eq``."""

    op: Literal["gt", "lt", "ge", "le", "eq"]
    lhs: Operand
    rhs: Operand


@dataclass(frozen=True)
class CrossCondition:
    """Directional crossover between two series.

    ``count``/``window`` extend the primitive to "crossed at least ``count``
    times within the trailing ``window`` bars". A *crossing* is a single
    directional crossover (sign change of ``lhs - rhs`` in the condition's
    direction), counted **same-direction** only. The defaults ``count=1``,
    ``window=1`` reproduce today's single-bar crossover BYTE-IDENTICALLY: a
    trailing window of one bar holds only the current bar's crossing, so
    ``count>=1`` is exactly the current ``fired[t]`` pulse. The engine routes
    the default case to the unchanged crossover computation and only runs the
    trailing-cumsum path when ``count>1 or window>1``.
    """

    op: Literal["cross_above", "cross_below"]
    lhs: Operand
    rhs: Operand
    count: int = 1
    window: int = 1


@dataclass(frozen=True)
class InRangeCondition:
    """``min <= operand <= max`` (all three resolved as series)."""

    op: Literal["in_range"]
    operand: Operand
    min: Operand
    max: Operand


@dataclass(frozen=True)
class RollingCondition:
    """``operand[t] <op> operand[t - lookback]`` for ``rolling_gt|rolling_lt``."""

    op: Literal["rolling_gt", "rolling_lt"]
    operand: Operand
    lookback: int


Condition = CompareCondition | CrossCondition | InRangeCondition | RollingCondition


# ---------------------------------------------------------------------------
# Block / Rules / Signal
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Block:
    """A single AND-block of conditions (v4).

    Fields:
      * ``id`` -- stable identifier (UUID) supplied by the caller. Used
        for trace/event identification and internal latch keying.
        ``""`` is the sentinel "not yet picked" (evaluator skips the
        block).
      * ``name`` -- user-editable display name. On entry blocks this
        name is the handle that exit blocks reference via
        ``target_entry_block_names``. Two entry blocks sharing the same
        non-empty name within a signal is ambiguous and rejected at the
        API layer. An empty name means the entry cannot be referenced
        by any exit.
      * ``input_id`` -- **entry blocks only**: id of the declared
        :class:`Input` whose instrument this block's position
        contributes to. ``""`` is the sentinel "not yet picked".
        MUST be empty (``""``) on exit blocks — the exit's operating
        input is derived from the target entry's ``input_id`` at
        validation/execution time. API validation rejects exit blocks
        with a non-empty ``input_id``.
      * ``weight`` -- signed percentage in ``[-100, +100]``. For entry
        blocks the latched contribution is ``sign(weight) * |weight| /
        100``; ``0.0`` is the sentinel "not yet picked" (rejected by
        API validation). Ignored on exit blocks.
      * ``target_entry_block_names`` -- for exit blocks only: the names
        of the entry blocks whose latches this exit clears (one or
        more). When the exit fires, every currently-latched targeted
        entry is cleared at the same bar; targets may span multiple
        inputs. Empty tuple ``()`` on entry blocks.
    """

    conditions: tuple[Condition, ...] = ()
    input_id: str = ""
    weight: float = 0.0
    id: str = ""
    name: str = ""
    target_entry_block_names: tuple[str, ...] = ()
    enabled: bool = True
    description: str = ""
    # Per-block reset binding (entries/exits only — reset blocks MUST keep
    # this None; the API rejects otherwise). When non-None, references the
    # ``id`` of a reset block in the same signal's ``rules.resets``: after
    # this block fires, its per-block arm is disarmed and re-armed only
    # when the bound reset fires. Default ``None`` means "no gate" (unconditional
    # firing — entry triggers whenever its condition is true).
    requires_reset_block_id: str | None = None
    # Cumulative re-arm count for the binding above (entries/exits only —
    # reset blocks MUST keep the default 1; the API rejects a non-default
    # on resets). Meaningful only when ``requires_reset_block_id`` is set:
    # after this block disarms, the bound reset must fire this many times
    # (CUMULATIVE, gaps allowed) before the per-block arm is restored. The
    # countdown is re-seeded on every disarm. Default ``1`` reproduces the
    # original single-flip re-arm exactly.
    requires_reset_count: int = 1
    # Optional bounded TEMPORAL chain over this block's conditions
    # (entries/exits only — reset blocks MUST keep this None; the API rejects
    # otherwise). ``links`` maps the index of a SUCCESSOR condition (1..len-1,
    # in the block's ``conditions`` order) to the ``within`` window in BARS,
    # measured from the immediately-preceding matched event. A non-empty
    # ``links`` turns the block from simultaneous CNF into ONE linear chain
    # A -(W1)-> B -(W2)-> C: the keys must form a single contiguous forward
    # chain (e.g. {1: W1, 2: W2}), windows must be finite and > 0, and no
    # nesting is allowed (validated at the API layer, HTTP 400). ``None``/empty
    # ⇒ today's zero-link CNF (the engine takes the literal unchanged latch
    # path). A link window of 0 is rejected at the API layer (W=0 folds to
    # plain AND, i.e. a non-link). Strictly-after semantics: the successor must
    # match on a LATER bar (>=1 after) the predecessor's match, within the
    # window; the block fires as an IMPULSE on the completion bar; a single
    # forward-only in-flight candidate; NaN on any chain operand aborts the
    # candidate.
    links: dict[int, int] | None = None


@dataclass(frozen=True)
class Trade:
    """A single round-trip (or still-open) trade.

    Derived from the engine's entry/exit latch pairing at end of run. One
    record per latch-open event on an enabled entry block; ``exit_*`` and
    ``close_bar`` are ``None`` when the position is still open at the
    last bar.

    ``signed_weight`` is always in FRACTION units (typically 0.0 … 1.0 for
    unleveraged exposure, possibly outside that range for leveraged
    legs). The portfolio aggregation layer converts the user-facing
    percent allocation to a fraction before stamping it onto a Trade —
    do not mix percent and fraction across this boundary.

    ``holding_id`` / ``holding_name`` are stamped by the portfolio
    aggregation layer when a Trade is surfaced through a multi-leg
    response; both remain ``None`` for the single-signal response shape.
    """

    input_id: str
    entry_block_id: str
    entry_block_name: str
    exit_block_id: str | None
    exit_block_name: str | None
    open_bar: int
    close_bar: int | None
    direction: str
    signed_weight: float
    holding_id: str | None = None
    holding_name: str | None = None


@dataclass(frozen=True)
class SignalRules:
    """Unified entries/exits + optional per-block reset bindings.

    ``resets`` is a list of named OR-blocks that entries and exits may
    bind to via ``Block.requires_reset_block_id``. Each bound block has
    its own per-block arm (``block_arm[block.id]``); after that block
    fires, its arm is disarmed and re-armed only when the bound reset
    fires. Blocks without a binding have NO reset gate. A reset block
    that no entry/exit binds to fires decoratively (its ``fired_indices``
    still records bars) but its ``latched_indices`` records ONLY bars
    where ≥1 bound block transitioned False→True via this fire.

    Reset blocks reuse :class:`Block` verbatim but only honour
    ``id``/``name``/``conditions``/``enabled``/``description`` — they
    must not carry ``input_id``, ``weight``, ``target_entry_block_names``,
    ``requires_reset_block_id``, or a non-default ``requires_reset_count``
    (the API layer rejects such payloads).
    """

    entries: tuple[Block, ...] = ()
    exits: tuple[Block, ...] = ()
    resets: tuple[Block, ...] = ()


@dataclass(frozen=True)
class Signal:
    """A signal spec — declared inputs + entries/exits rules.

    ``inputs`` is a tuple of :class:`Input`. Blocks and operands bind
    through these inputs by id.
    """

    id: str
    name: str
    inputs: tuple[Input, ...] = ()
    rules: SignalRules = field(default_factory=SignalRules)


__all__ = [
    "Block",
    "CompareCondition",
    "Condition",
    "ConstantOperand",
    "CrossCondition",
    "IndicatorOperand",
    "Input",
    "InputInstrument",
    "InRangeCondition",
    "InstrumentBasket",
    "InstrumentContinuous",
    "InstrumentOperand",
    "InstrumentOptionStream",
    "InstrumentSpot",
    "Operand",
    "OptionStreamLabel",
    "RollingCondition",
    "Signal",
    "SignalRules",
    "Trade",
]
