"""Signal specification types -- v4 (unified Entries/Exits, signed weights).

A ``Signal`` is an OR of AND-blocks of boolean conditions split into two
sections: ``entries`` and ``exits``. Each entry block has a **signed**
weight in ``[-100, +100]`` (percentage of capital, sign decides long/
short). Each exit block references exactly one entry block via
``target_entry_block_name`` and, when its conditions latch, clears only
that entry's latch.

v4 contract (breaks v3 — no migration, no compat shims)
-------------------------------------------------------
* ``SignalRules`` now has ``entries: tuple[Block, ...]`` and
  ``exits: tuple[Block, ...]``. The v3 four-direction split is gone.
* ``Block`` carries a stable ``id: str`` (UUID generated by the
  frontend on block creation), a user-editable ``name: str``, a signed
  ``weight``, and — on exit blocks only — a
  ``target_entry_block_name: str`` referencing the ``name`` of an
  entry block declared in the same signal's rules.
* Exits clear the latch of the single entry block identified by
  ``target_entry_block_name`` — never "all latches under the same input".
* Entries use ``sign(weight)`` as direction. ``weight == 0`` on entry
  blocks is invalid (meaningless, matches the old strictly-positive
  constraint transposed).

Inputs are still a top-level list; blocks and operands still bind
through ``input_id``. Instrument and indicator operand resolution are
unchanged from v3.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

from tcg.types.options import MaturitySpec, SelectionCriterion


# ---------------------------------------------------------------------------
# Input instrument (discriminated union)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class InstrumentSpot:
    """Spot instrument — a single (collection, instrument_id)."""

    collection: str
    instrument_id: str
    kind: Literal["spot"] = "spot"


@dataclass(frozen=True)
class InstrumentContinuous:
    """Continuous-futures instrument — rolled from a FUT_* collection."""

    collection: str
    adjustment: Literal["none", "ratio", "difference"] = "none"
    cycle: str | None = None  # e.g. "HMUZ" quarterly
    roll_offset: int = 0
    strategy: Literal["front_month"] = "front_month"
    kind: Literal["continuous"] = "continuous"


# Streams readable off a single option contract row.  Mirrors the engine
# ``StreamLabel`` and the API ``OptionStreamLabel`` — redeclared here so
# the types layer has no dependency on engine or core.
OptionStreamLabel = Literal[
    "mid",
    "iv",
    "delta",
    "gamma",
    "vega",
    "theta",
    "open_interest",
    "volume",
]


@dataclass(frozen=True)
class InstrumentOptionStream:
    """Option-stream instrument — materialises a 1-D float stream off a
    selected option contract on each trade date.

    Uses the same maturity/selection/stream vocabulary as the indicator
    and options routers so a signal can bind to an option-derived series
    (e.g. 25-delta put IV, front-month mid price) without inventing a
    parallel spec.
    """

    collection: str
    option_type: Literal["C", "P"]
    cycle: str | None
    maturity: MaturitySpec
    selection: SelectionCriterion
    stream: OptionStreamLabel
    kind: Literal["option_stream"] = "option_stream"


InputInstrument = InstrumentSpot | InstrumentContinuous | InstrumentOptionStream


@dataclass(frozen=True)
class Input:
    """A named price-series input declared at the top of a signal.

    ``id`` is typically a single letter (X, Y, Z, ...) assigned
    automatically on creation and user-renameable. ``instrument`` is the
    fully-configured source; an unconfigured input (missing collection
    or instrument_id, missing cycle/adjustment for continuous) is not
    runnable.
    """

    id: str
    instrument: InputInstrument


# ---------------------------------------------------------------------------
# Operand
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class IndicatorOperand:
    """Operand backed by a user-defined indicator.

    ``input_id`` identifies the bound input; the input's instrument
    replaces the indicator's primary series-map instrument at execution
    time. ``series_override`` maps ``label -> input_id`` to rebind
    non-primary labels to other declared inputs. ``params_override``
    maps ``param_name -> value``.
    """

    indicator_id: str
    input_id: str
    output: str = "default"
    params_override: dict[str, Any] | None = None
    series_override: dict[str, str] | None = None  # label -> input_id
    kind: Literal["indicator"] = "indicator"


@dataclass(frozen=True)
class InstrumentOperand:
    """Operand backed by an input's price field (default: ``close``).

    ``input_id`` references one of the signal's declared inputs; the
    operand resolves through that input's bound instrument.
    """

    input_id: str
    field: str = "close"
    kind: Literal["instrument"] = "instrument"


@dataclass(frozen=True)
class ConstantOperand:
    """Operand backed by a constant scalar broadcast across all timesteps."""

    value: float
    kind: Literal["constant"] = "constant"


Operand = IndicatorOperand | InstrumentOperand | ConstantOperand


# ---------------------------------------------------------------------------
# Condition variants (unchanged vs v2)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CompareCondition:
    """Binary comparison: ``lhs <op> rhs`` for ``gt|lt|ge|le|eq``."""

    op: Literal["gt", "lt", "ge", "le", "eq"]
    lhs: Operand
    rhs: Operand


@dataclass(frozen=True)
class CrossCondition:
    """Directional crossover between two series."""

    op: Literal["cross_above", "cross_below"]
    lhs: Operand
    rhs: Operand


@dataclass(frozen=True)
class InRangeCondition:
    """``min <= operand <= max`` (all three resolved as series)."""

    op: Literal["in_range"]
    operand: Operand
    min: Operand
    max: Operand


@dataclass(frozen=True)
class RollingCondition:
    """``operand[t] <op> operand[t - lookback]`` for ``rolling_gt|rolling_lt``."""

    op: Literal["rolling_gt", "rolling_lt"]
    operand: Operand
    lookback: int


Condition = CompareCondition | CrossCondition | InRangeCondition | RollingCondition


# ---------------------------------------------------------------------------
# Block / Rules / Signal
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Block:
    """A single AND-block of conditions (v4).

    Fields:
      * ``id`` -- stable identifier (UUID) supplied by the caller. Used
        for trace/event identification and internal latch keying.
        ``""`` is the sentinel "not yet picked" (evaluator skips the
        block).
      * ``name`` -- user-editable display name. On entry blocks this
        name is the handle that exit blocks reference via
        ``target_entry_block_name``. Two entry blocks sharing the same
        non-empty name within a signal is ambiguous and rejected at the
        API layer. An empty name means the entry cannot be referenced
        by any exit.
      * ``input_id`` -- **entry blocks only**: id of the declared
        :class:`Input` whose instrument this block's position
        contributes to. ``""`` is the sentinel "not yet picked".
        MUST be empty (``""``) on exit blocks — the exit's operating
        input is derived from the target entry's ``input_id`` at
        validation/execution time. API validation rejects exit blocks
        with a non-empty ``input_id``.
      * ``weight`` -- signed percentage in ``[-100, +100]``. For entry
        blocks the latched contribution is ``sign(weight) * |weight| /
        100``; ``0.0`` is the sentinel "not yet picked" (rejected by
        API validation). Ignored on exit blocks.
      * ``target_entry_block_name`` -- for exit blocks only: name of
        the single entry block whose latch this exit clears.
        ``None``/``""`` on entry blocks.
    """

    conditions: tuple[Condition, ...] = ()
    input_id: str = ""
    weight: float = 0.0
    id: str = ""
    name: str = ""
    target_entry_block_name: str | None = None
    enabled: bool = True
    description: str = ""
    # Per-block reset binding (entries/exits only — reset blocks MUST keep
    # this None; the API rejects otherwise). When non-None, references the
    # ``id`` of a reset block in the same signal's ``rules.resets``: after
    # this block fires, its per-block arm is disarmed and re-armed only
    # when the bound reset fires. Default ``None`` means "no gate" (the
    # pre-Task-1 unconditional firing behavior).
    requires_reset_block_id: str | None = None


@dataclass(frozen=True)
class Trade:
    """A single round-trip (or still-open) trade.

    Derived from the engine's entry/exit latch pairing at end of run. One
    record per latch-open event on an enabled entry block; ``exit_*`` and
    ``close_bar`` are ``None`` when the position is still open at the
    last bar.

    ``signed_weight`` is always in FRACTION units (typically 0.0 … 1.0 for
    unleveraged exposure, possibly outside that range for leveraged
    legs). The portfolio aggregation layer converts the user-facing
    percent allocation to a fraction before stamping it onto a Trade —
    do not mix percent and fraction across this boundary.

    ``holding_id`` / ``holding_name`` are stamped by the portfolio
    aggregation layer when a Trade is surfaced through a multi-leg
    response; both remain ``None`` for the single-signal response shape.
    """

    input_id: str
    entry_block_id: str
    entry_block_name: str
    exit_block_id: str | None
    exit_block_name: str | None
    open_bar: int
    close_bar: int | None
    direction: str
    signed_weight: float
    holding_id: str | None = None
    holding_name: str | None = None


@dataclass(frozen=True)
class SignalRules:
    """Unified entries/exits + optional per-block reset bindings.

    ``resets`` is a list of named OR-blocks that entries and exits may
    bind to via ``Block.requires_reset_block_id``. Each bound block has
    its own per-block arm (``block_arm[block.id]``); after that block
    fires, its arm is disarmed and re-armed only when the bound reset
    fires. Blocks without a binding have NO reset gate. A reset block
    that no entry/exit binds to fires decoratively (its ``fired_indices``
    still records bars) but its ``latched_indices`` records ONLY bars
    where ≥1 bound block transitioned False→True via this fire.

    Reset blocks reuse :class:`Block` verbatim but only honour
    ``id``/``name``/``conditions``/``enabled``/``description`` — they
    must not carry ``input_id``, ``weight``, ``target_entry_block_name``,
    or ``requires_reset_block_id`` (the API layer rejects such payloads).
    """

    entries: tuple[Block, ...] = ()
    exits: tuple[Block, ...] = ()
    resets: tuple[Block, ...] = ()


@dataclass(frozen=True)
class Signal:
    """A signal spec — declared inputs + entries/exits rules.

    ``inputs`` is a tuple of :class:`Input`. Blocks and operands bind
    through these inputs by id.
    """

    id: str
    name: str
    inputs: tuple[Input, ...] = ()
    rules: SignalRules = field(default_factory=SignalRules)


__all__ = [
    "Block",
    "CompareCondition",
    "Condition",
    "ConstantOperand",
    "CrossCondition",
    "IndicatorOperand",
    "Input",
    "InputInstrument",
    "InRangeCondition",
    "InstrumentContinuous",
    "InstrumentOperand",
    "InstrumentOptionStream",
    "InstrumentSpot",
    "Operand",
    "OptionStreamLabel",
    "RollingCondition",
    "Signal",
    "SignalRules",
    "Trade",
]
