"""Signal specification types -- v4 (unified Entries/Exits, signed weights).

A ``Signal`` is an OR of AND-blocks of boolean conditions split into two
sections: ``entries`` and ``exits``. Each entry block has a **signed**
weight in ``[-100, +100]`` (percentage of capital, sign decides long/
short). Each exit block references exactly one entry block via
``target_entry_block_id`` and, when its conditions latch, clears only
that entry's latch.

v4 contract (breaks v3 — no migration, no compat shims)
-------------------------------------------------------
* ``SignalRules`` now has ``entries: tuple[Block, ...]`` and
  ``exits: tuple[Block, ...]``. The v3 four-direction split is gone.
* ``Block`` carries a stable ``id: str`` (UUID generated by the
  frontend on block creation), a signed ``weight``, and — on exit
  blocks only — a ``target_entry_block_id: str`` referencing the id of
  an entry block declared in the same signal's rules.
* Exits clear the latch of the single entry block identified by
  ``target_entry_block_id`` — never "all latches under the same input".
* Entries use ``sign(weight)`` as direction. ``weight == 0`` on entry
  blocks is invalid (meaningless, matches the old strictly-positive
  constraint transposed).

Inputs are still a top-level list; blocks and operands still bind
through ``input_id``. Instrument and indicator operand resolution are
unchanged from v3.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal


# ---------------------------------------------------------------------------
# Input instrument (discriminated union)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class InstrumentSpot:
    """Spot instrument — a single (collection, instrument_id)."""

    collection: str
    instrument_id: str
    kind: Literal["spot"] = "spot"


@dataclass(frozen=True)
class InstrumentContinuous:
    """Continuous-futures instrument — rolled from a FUT_* collection."""

    collection: str
    adjustment: Literal["none", "proportional", "difference"] = "none"
    cycle: str | None = None  # e.g. "HMUZ" quarterly
    roll_offset: int = 0
    strategy: Literal["front_month"] = "front_month"
    kind: Literal["continuous"] = "continuous"


InputInstrument = InstrumentSpot | InstrumentContinuous


@dataclass(frozen=True)
class Input:
    """A named price-series input declared at the top of a signal.

    ``id`` is typically a single letter (X, Y, Z, ...) assigned
    automatically on creation and user-renameable. ``instrument`` is the
    fully-configured source; an unconfigured input (missing collection
    or instrument_id, missing cycle/adjustment for continuous) is not
    runnable.
    """

    id: str
    instrument: InputInstrument


# ---------------------------------------------------------------------------
# Operand
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class IndicatorOperand:
    """Operand backed by a user-defined indicator.

    ``input_id`` identifies the bound input; the input's instrument
    replaces the indicator's primary series-map instrument at execution
    time. ``series_override`` maps ``label -> input_id`` to rebind
    non-primary labels to other declared inputs. ``params_override``
    maps ``param_name -> value``.
    """

    indicator_id: str
    input_id: str
    output: str = "default"
    params_override: dict[str, Any] | None = None
    series_override: dict[str, str] | None = None  # label -> input_id
    kind: Literal["indicator"] = "indicator"


@dataclass(frozen=True)
class InstrumentOperand:
    """Operand backed by an input's price field (default: ``close``).

    ``input_id`` references one of the signal's declared inputs; the
    operand resolves through that input's bound instrument.
    """

    input_id: str
    field: str = "close"
    kind: Literal["instrument"] = "instrument"


@dataclass(frozen=True)
class ConstantOperand:
    """Operand backed by a constant scalar broadcast across all timesteps."""

    value: float
    kind: Literal["constant"] = "constant"


Operand = IndicatorOperand | InstrumentOperand | ConstantOperand


# ---------------------------------------------------------------------------
# Condition variants (unchanged vs v2)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CompareCondition:
    """Binary comparison: ``lhs <op> rhs`` for ``gt|lt|ge|le|eq``."""

    op: Literal["gt", "lt", "ge", "le", "eq"]
    lhs: Operand
    rhs: Operand


@dataclass(frozen=True)
class CrossCondition:
    """Directional crossover between two series."""

    op: Literal["cross_above", "cross_below"]
    lhs: Operand
    rhs: Operand


@dataclass(frozen=True)
class InRangeCondition:
    """``min <= operand <= max`` (all three resolved as series)."""

    op: Literal["in_range"]
    operand: Operand
    min: Operand
    max: Operand


@dataclass(frozen=True)
class RollingCondition:
    """``operand[t] <op> operand[t - lookback]`` for ``rolling_gt|rolling_lt``."""

    op: Literal["rolling_gt", "rolling_lt"]
    operand: Operand
    lookback: int


Condition = CompareCondition | CrossCondition | InRangeCondition | RollingCondition


# ---------------------------------------------------------------------------
# Block / Rules / Signal
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Block:
    """A single AND-block of conditions (v4).

    Fields:
      * ``id`` -- stable identifier (UUID) supplied by the caller. On
        entries this id is targeted by exits; on exits this id is used
        only for trace/event identification. ``""`` is the sentinel
        "not yet picked" (evaluator skips the block).
      * ``input_id`` -- id of the declared :class:`Input` whose
        instrument this block's position contributes to. ``""`` is the
        sentinel "not yet picked".
      * ``weight`` -- signed percentage in ``[-100, +100]``. For entry
        blocks the latched contribution is ``sign(weight) * |weight| /
        100``; ``0.0`` is the sentinel "not yet picked" (rejected by
        API validation). Ignored on exit blocks.
      * ``target_entry_block_id`` -- for exit blocks only: id of the
        single entry block whose latch this exit clears. ``None``/``""``
        on entry blocks.
    """

    conditions: tuple[Condition, ...] = ()
    input_id: str = ""
    weight: float = 0.0
    id: str = ""
    target_entry_block_id: str | None = None


@dataclass(frozen=True)
class SignalRules:
    """Unified entries/exits (v4): two OR-lists of AND-blocks."""

    entries: tuple[Block, ...] = ()
    exits: tuple[Block, ...] = ()


@dataclass(frozen=True)
class Signal:
    """A signal spec — declared inputs + entries/exits rules.

    ``inputs`` is a tuple of :class:`Input`. Blocks and operands bind
    through these inputs by id.
    """

    id: str
    name: str
    inputs: tuple[Input, ...] = ()
    rules: SignalRules = field(default_factory=SignalRules)


__all__ = [
    "Block",
    "CompareCondition",
    "Condition",
    "ConstantOperand",
    "CrossCondition",
    "IndicatorOperand",
    "Input",
    "InputInstrument",
    "InRangeCondition",
    "InstrumentContinuous",
    "InstrumentOperand",
    "InstrumentSpot",
    "Operand",
    "RollingCondition",
    "Signal",
    "SignalRules",
]
